name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
env:
  FASMG_DOMAIN: https://flatassembler.net
  BIN_PATH: ${{github.workspace}}/exec
  REPO_PATH: ${{github.workspace}}/project
  FASMG_PATH: ${{github.workspace}}/fasmg

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu]
        include:
          - nul: /dev/null
          - runs-on: ubuntu
            fasmg: /fasmg.x64
    runs-on: ${{matrix.runs-on}}-latest

    steps:
      - name: Prepare Build Environment
        run: cmake -E echo >> $${{matrix.env}}GITHUB_PATH ${{env.BIN_PATH}}

      - name: Download convbin
        uses: actions/checkout@v3
        with:
          repository: 'mateoconlechuga/convbin'
          path: ${{github.workspace}}/convbin
          submodules: recursive
          persist-credentials: false
      - name: Build convbin
        run: |
          make -C ${{github.workspace}}/convbin all V=1
      - name: Setup convbin
        run: cmake -E copy ${{github.workspace}}/convbin/bin/convbin ${{env.BIN_PATH}}/convbin${{matrix.exe}}

      - name: Download Fasmg Download Page
        id: fasmg-download
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.FASMG_DOMAIN}}/download.php
      - name: Parse Fasmg Download Page
        id: fasmg-url
        uses: QwerMike/xpath-action@v1
        with:
          filename: ${{steps.fasmg-download.outputs.file-path}}
          expression: //a[starts-with(text(),"flat assembler g ")]/@href
      - name: Extract Fasmg Url
        run: cmake -E echo >> $${{matrix.env}}GITHUB_ENV ${{steps.fasmg-url.outputs.result}}
      - name: Download Fasmg
        id: fasmg
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{env.FASMG_DOMAIN}}/${{env.href}}
      - name: Extract Fasmg
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{steps.fasmg.outputs.file-path}}
          pathTarget: ${{env.FASMG_PATH}}
      - name: Setup Fasmg
        run: cmake -E copy fasmg${{matrix.fasmg}} ${{env.BIN_PATH}}/fasmg${{matrix.exe}}

      - name: Make Binaries Executable
        if: runner.os != 'Windows'
        run: chmod +x ${{env.BIN_PATH}}/*
      - name: Test Build Dependencies
        run: |
          fasmg ${{matrix.nul}} ${{matrix.nul}}

      - name: Checkout Program
        uses: actions/checkout@v3
        with:
          path: ${{env.REPO_PATH}}
          submodules: recursive
          persist-credentials: false

      - name: Build Program
        run: |
          make -C ${{env.REPO_PATH}} release V=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.repository.name}}
          path: ${{env.REPO_PATH}}/${{github.event.repository.name}}.zip
